- selvpc/doc.go
- selvpc/selvpc.go
- selvpc/testing/client_test.go
- selvpc/testutils/environment.go
- selvpc/testutils/fakes.go
Add client with basic methods and structures that will be used by all
subpackages of the selvpc library.
For #1.
> Add basic service client

- selvpc/resell/doc.go
- selvpc/resell/resell.go
- selvpc/resell/v2/client.go
- selvpc/resell/v2/doc.go
- selvpc/testutils/clients.go
Add service client for the Resell v2 API. Also provide a test client  that can be used with unit tests.
For #4.
> Add the Resell v2 service client

- .travis.yml
- scripts/test
> Add coveralls.io support

- selvpcclient/resell/v2/users/doc.go
- selvpcclient/resell/v2/users/requests.go
- selvpcclient/resell/v2/users/requests_opts.go
- selvpcclient/resell/v2/users/testing/fixtures.go
- selvpcclient/resell/v2/users/testing/requests_test.go
Add method to create a Resell V2 user.
Add structure with user create options, docs example and test.
For #17
> Add Resell V2 user create method

- selvpcclient/resell/v2/users/testing/requests_test.go
Verify HTTP methods in the "users" package.
For #17
> Resell V2 Users: test HTTP methods

- selvpcclient/resell/v2/floatingips/doc.go
- selvpcclient/resell/v2/floatingips/requests.go
- selvpcclient/resell/v2/floatingips/schemas.go
- selvpcclient/resell/v2/floatingips/testing/fixtures.go
- selvpcclient/resell/v2/floatingips/testing/request_test.go
- selvpcclient/resell/v2/servers/doc.go
- selvpcclient/resell/v2/servers/schemas.go
Add GET method for the floating ip.
Add Server package that provides common structure for the floatingips
and subnets package.
Add doc example and test.
For #29
> Add Resell V2 floating ip GET method

- selvpcclient/resell/v2/floatingips/doc.go
- selvpcclient/resell/v2/floatingips/requests.go
- selvpcclient/resell/v2/floatingips/testing/request_test.go
Provide a way to delete a single floating ip, add test and doc example.
For #29
> Add Resell V2 floating ip Delete method

- selvpcclient/resell/v2/subnets/doc.go
- selvpcclient/resell/v2/subnets/requests.go
- selvpcclient/resell/v2/subnets/testing/fixtures.go
- selvpcclient/resell/v2/subnets/testing/request_test.go
Add List method with tests and doc example.
Also fix prefixes in testing fixtures.
For #30
> Resell V2 - add subnets List method

- selvpcclient/resell/v2/subnets/doc.go
- selvpcclient/resell/v2/subnets/request_opts.go
- selvpcclient/resell/v2/subnets/requests.go
- selvpcclient/resell/v2/subnets/testing/fixtures.go
- selvpcclient/resell/v2/subnets/testing/request_test.go
- selvpcclient/selvpc.go
Add Create method for the Subnets package.
Add tests and doc example.
For #30
> Resell V2 API - add subnets Create method

- selvpcclient/resell/v2/client.go
- selvpcclient/resell/v2/client_test.go
Users may want to use custom endpoint for the Resell V2 API.
This commit adds a new NewV2ResellClientWithEndpoint method, fixes
argument capitalization in the old NewV2ResellClient method and adds
simple tests.
For #18
> Resell V2 - add client with a custom endpoint

- selvpcclient/resell/v2/floatingips/testing/request_test.go
- selvpcclient/resell/v2/licenses/testing/requests_test.go
- selvpcclient/resell/v2/projects/testing/requests_test.go
- selvpcclient/resell/v2/quotas/testing/requests_test.go
- selvpcclient/resell/v2/subnets/testing/request_test.go
- selvpcclient/resell/v2/users/testing/requests_test.go
- selvpcclient/testutils/handlers.go
Move all HTTP endpoint handlers to the testutils package and refactor
tests.
For #54
> Resell V2 tests - move all reusable handlers

- selvpcclient/resell/v2/projects/testing/fixtures.go
- selvpcclient/resell/v2/projects/testing/requests_test.go
- selvpcclient/resell/v2/quotas/testing/fixtures.go
- selvpcclient/resell/v2/quotas/testing/requests_test.go
- selvpcclient/resell/v2/subnets/testing/request_test.go
Add tests for the error cases.
For #54
> Resell V2 projects - add more tests

- selvpcclient/resell/resell.go
- selvpcclient/selvpc.go
This commit moves the application name and resell service type to
separate constants so they can be reused.
> Move some hardcoded values to separated constants

- selvpcclient/resell/v2/licenses/requests.go
- selvpcclient/resell/v2/licenses/requests_opts.go
- selvpcclient/resell/v2/licenses/testing/requests_test.go
Allow to get detailed list of licenses.
For #73
> Licenses: add query parameters to the List method

- selvpcclient/resell/v2/floatingips/requests.go
- selvpcclient/resell/v2/floatingips/requests_opts.go
- selvpcclient/resell/v2/floatingips/testing/requests_test.go
Allow to get detailed list of floating IPs, update unit tests.
For #73
> FloatingIPs: add query params to the List method

- selvpcclient/resell/v2/subnets/requests.go
- selvpcclient/resell/v2/subnets/requests_opts.go
- selvpcclient/resell/v2/subnets/testing/requests_test.go
Allow to get detailed list of subnets, update unit tests.
For #73
> Subnets: add query params to the List method

- selvpcclient/resell/v2/floatingips/doc.go
- selvpcclient/resell/v2/licenses/doc.go
- selvpcclient/resell/v2/subnets/doc.go
Fix List method examples for packages that needs passing of ListOpts
structure into their List methods.
> Docs: fix docs for floatingips, licenses, subnets

- selvpcclient/resell/v2/projects/testing/requests_test.go
Some of the tests in the projects package had invalid names.
This commit fixes it.
> Resell V2: rename projects tests

- selvpcclient/resell/v2/capabilities/requests.go
- selvpcclient/resell/v2/capabilities/testing/requests_test.go
- selvpcclient/resell/v2/floatingips/requests.go
- selvpcclient/resell/v2/floatingips/testing/requests_test.go
- selvpcclient/resell/v2/licenses/requests.go
- selvpcclient/resell/v2/licenses/testing/requests_test.go
- selvpcclient/resell/v2/projects/requests.go
- selvpcclient/resell/v2/projects/testing/requests_test.go
- selvpcclient/resell/v2/quotas/requests.go
- selvpcclient/resell/v2/quotas/requests_opts.go
- selvpcclient/resell/v2/quotas/testing/requests_test.go
- selvpcclient/resell/v2/roles/requests.go
- selvpcclient/resell/v2/roles/testing/requests_test.go
- selvpcclient/resell/v2/subnets/requests.go
- selvpcclient/resell/v2/subnets/testing/requests_test.go
- selvpcclient/resell/v2/tokens/requests.go
- selvpcclient/resell/v2/tokens/testing/requests_test.go
- selvpcclient/resell/v2/traffic/requests.go
- selvpcclient/resell/v2/traffic/testing/requests_test.go
- selvpcclient/resell/v2/users/requests.go
- selvpcclient/resell/v2/users/testing/requests_test.go
- selvpcclient/resell/v2/vrrpsubnets/requests.go
- selvpcclient/resell/v2/vrrpsubnets/testing/fixtures.go
- selvpcclient/resell/v2/vrrpsubnets/testing/requests_test.go
- selvpcclient/selvpc.go
- selvpcclient/testing/client_test.go
- selvpcclient/testutils/handlers.go
Use standard HTTP method names from the `net/http` package.
Remove `emptyFmt` errors.
Refactor testutils handlers so it will use structure with parameters instead of many arguments in each handler. This structure is passed by pointer to prevent lots of copying.
> Refactor hardcoded methods, emptyFmt and testutils

- .travis.yml
Use "-withExperimental" and "-withOpinionated" arguments to enable
strict checking.
> CI: run Gocritic with all checks

- .travis.yml
Use "golang.org/x/lint/golint" for Golint.
> TravisCI: change golint URL

- selvpcclient/resell/v2/licenses/testing/fixtures.go
- selvpcclient/resell/v2/projects/testing/fixtures.go
- selvpcclient/resell/v2/subnets/testing/fixtures.go
- selvpcclient/resell/v2/vrrpsubnets/testing/fixtures.go
Ensure key order in unit tests.
For #97
> Gocritic: fix structLitKeyOrder errors

- selvpcclient/resell/v2/client.go
- selvpcclient/selvpc.go
Use customized timeouts for HTTP client instead of default Go net/http timeouts.
For #101
> HTTP client: use custom timeouts

- selvpcclient/selvpc.go
Use 40 second for the defaultHTTPTimeout constant.
For #101
> SelVPC HTTP client: set higher defaultHTTPTimeout

- selvpcclient/selvpc.go
Set higher default HTTP timeout, tune client's transport to use newer
net.DialContext instead of deprecated net.Dial and fix inline comments.
For #108
> HTTP: tune client timeouts used by all requests.

- selvpcclient/selvpc.go
Set higher default HTTP timeouts to prevent errors.
For #108
> HTTP client: set higher timeouts

- selvpcclient/resell/v2/roles/doc.go
- selvpcclient/resell/v2/roles/requests.go
- selvpcclient/resell/v2/roles/testing/fixtures.go
- selvpcclient/resell/v2/roles/testing/requests_test.go
Add method to list all roles in the current domain.
Add tests and doc example.
For #107
> Resell V2 - add roles list method

- selvpcclient/resell/v2/keypairs/doc.go
- selvpcclient/resell/v2/keypairs/requests.go
- selvpcclient/resell/v2/keypairs/schemas.go
- selvpcclient/resell/v2/keypairs/testing/fixtures.go
- selvpcclient/resell/v2/keypairs/testing/requests_test.go
Add the "keypairs" package with a List method and a basic Keypair
structure.
Add tests and doc example.
For #110
> Resell V2 - add Keypairs List method)

- README.md
- selvpcclient/resell/v2/crossregionsubnets/doc.go
- selvpcclient/resell/v2/crossregionsubnets/requests.go
- selvpcclient/resell/v2/crossregionsubnets/schemas.go
- selvpcclient/resell/v2/crossregionsubnets/testing/fixtures.go
- selvpcclient/resell/v2/crossregionsubnets/testing/requests_test.go
- selvpcclient/resell/v2/subnets/schemas.go
* Resell V2 - add cross-region subnets Get method
Add crossregionsubnets package with Get method and basic CrossRegionSubnet structure.
* Readme: add cross-region subnets link
Add link to the "crossregionsubnets" package documentation.
For #106
> Resell V2 - add cross-region subnets Get method

- selvpcclient/testutils/handlers.go
* Put response writing after reading request body
* Add defered closing of the request body.
For #120
> Fix issue with response writing

- selvpcclient/resell/v2/crossregionsubnets/schemas.go
- selvpcclient/resell/v2/crossregionsubnets/testing/fixtures.go
Remove ProjectID field from associated subnets and add it into parent
Cross-region subnet.
> Resell V2: fix Cross-region subnet ProjectID

- selvpcclient/resell/v2/tokens/doc.go
- selvpcclient/resell/v2/tokens/requests.go
- selvpcclient/resell/v2/tokens/testing/requests_test.go
Support for enpoints _`HTTP DELETE`_ `tokens/<TOKEN_ID>`
> Add support enpoint for revoke token by its id

- selvpcclient/selvpc.go
Populate extended error message from the response body in case of error
status codes.
For #127
> Add extended error message to all requests

- selvpcclient/selvpc.go
Write extended error only if response body read was successful.
For #134
> Error response: fix extended error logic

- scripts/gotest.sh
- selvpcclient/resell/v2/projects/testing/fixtures.go
Fix empty quotas in fixtures.
Check if go test command is failed to select a valid exit code.
> Resell V2 Projects: fix tests with quotas

- .golangci.yml
- .travis.yml
- selvpcclient/resell/v2/keypairs/requests.go
- selvpcclient/resell/v2/roles/requests.go
- selvpcclient/resell/v2/traffic/testing/fixtures.go
Use Golangci-lint v1.30.0 in Travis CI.
Remove deprecated enable-all configuration from .golangci.yml.
Fix issues with gofumpt linter.
> Update and reconfigure golangci-lint

- .github/workflows/secure.yml
- .github/workflows/verify.yml
- .semgrepignore
- selvpcclient/resell/v2/keypairs/requests.go
- selvpcclient/resell/v2/keypairs/requests_opts.go
Added the ability to pass user_id as a filter to speed up the key list query.
Also fix GitHub Actions:
- enable for PR from fork
- add .semgrepignore for tests
- remove wrong --severity flag for semgrep
> Add keypairs list opts

- .golangci.yml
- selvpcclient/quotamanager/quotas/requests.go
- selvpcclient/quotamanager/quotas/testing/fixtures.go
- selvpcclient/quotamanager/quotas/testing/requests_test.go
Добавлена возможность указывать нужные ресурсы при вызове `quotas.GetProjectQuotas`  с помощью `quotas.WithResourceFilter`, например:
```
quotas.GetProjectQuotas(
client, 
"projectID", 
"region",
quotas.WithResourceFilter("resource_name1"),
quotas.WithResourceFilter("resource_name2"),
)
```
> Add ability to set filters to GetProjectQuotas method
