selectel/go-selvpcclient

selvpc/resell/v2/quotas/doc.go, selvpc/resell/v2/quotas/requests.go, selvpc/resell/v2/quotas/schemas.go, selvpc/resell/v2/quotas/testing/fixtures.go, selvpc/resell/v2/quotas/testing/requests_test.go
Implement GetAll method for quotas.
Add tests and documentation.
For #6.
=> Add Resell v2 quotas get all method

selvpc/resell/v2/quotas/doc.go, selvpc/resell/v2/quotas/requests.go, selvpc/resell/v2/quotas/testing/fixtures.go, selvpc/resell/v2/quotas/testing/requests_test.go
Implement GetFree method for quotas.
For #6.
=> Add Resell v2 quotas get free method

selvpc/resell/v2/quotas/doc.go, selvpc/resell/v2/quotas/requests.go, selvpc/resell/v2/quotas/schemas.go, selvpc/resell/v2/quotas/testing/fixtures.go, selvpc/resell/v2/quotas/testing/requests_test.go
Implement GetProjectsQuotas method and add ProjectsQuotas structure with a custom UnmarshalJSON method.
For #6.
=> Add Resell v2 get projects quotas method

selvpc/resell/v2/quotas/doc.go, selvpc/resell/v2/quotas/requests.go, selvpc/resell/v2/quotas/requests_opts.go, selvpc/resell/v2/quotas/testing/fixtures.go, selvpc/resell/v2/quotas/testing/requests_test.go
Implement UpdateProjectQuotas method and add separate structures with a custom MarshalJSON method to build a valid request body.
For #6.
=> Add Resell v2 update quotas for a project method

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
=> Add the contributor guide with a PR template

selvpcclient/resell/v2/projects/doc.go, selvpcclient/resell/v2/projects/requests.go, selvpcclient/resell/v2/projects/testing/fixtures.go, selvpcclient/resell/v2/projects/testing/requests_test.go
Add method to list all domain projects.
For #12
=> Add Resell V2 projects List method

selvpcclient/resell/v2/quotas/requests_opts.go, selvpcclient/resell/v2/quotas/testing/fixtures.go
Change Value type to the pointer so it not going to be set to 0 at every
update request.
=> Change ResourceQuotaOpts.Value type to *int

selvpcclient/resell/v2/projects/doc.go, selvpcclient/resell/v2/projects/requests.go, selvpcclient/resell/v2/projects/requests_opts.go, selvpcclient/resell/v2/projects/testing/fixtures.go, selvpcclient/resell/v2/projects/testing/requests_test.go
Add method to create a Resell V2 project.
Add structure with project create options, docs example and test.
For #12
=> Add Resell V2 project create method

selvpcclient/resell/v2/projects/doc.go, selvpcclient/resell/v2/projects/requests.go, selvpcclient/resell/v2/projects/testing/fixtures.go, selvpcclient/resell/v2/projects/testing/requests_test.go
Add a method to update a single Resell v2 project. Add tests and a
documentation example.
For #12
=> Add Resell V2 project update method

selvpcclient/resell/v2/projects/doc.go, selvpcclient/resell/v2/projects/requests.go, selvpcclient/resell/v2/projects/testing/requests_test.go
Implement an ability to delete a single project.
For #12
=> Add a delete method to Resell V2 project

selvpcclient/resell/v2/users/doc.go, selvpcclient/resell/v2/users/requests.go, selvpcclient/resell/v2/users/testing/fixtures.go, selvpcclient/resell/v2/users/testing/requests_test.go
=> Resell v2 user update

selvpcclient/resell/v2/users/doc.go, selvpcclient/resell/v2/users/requests.go, selvpcclient/resell/v2/users/testing/requests_test.go
Implement an ability to delete a single project.
For #17
=> Add a delete method to Resell V2 user

selvpcclient/resell/v2/projects/testing/requests_test.go
Verify HTTP methods in the "projects" package.
=> Resell V2 Projects: test HTTP methods

selvpcclient/resell/v2/quotas/testing/requests_test.go
Verify HTTP methods in the "quotas" package.
=> Resell V2 Quotas: test HTTP methods

selvpcclient/resell/v2/floatingips/doc.go, selvpcclient/resell/v2/floatingips/requests.go, selvpcclient/resell/v2/floatingips/schemas.go, selvpcclient/resell/v2/floatingips/testing/fixtures.go, selvpcclient/resell/v2/floatingips/testing/request_test.go
Add package to work with floatingips of the Resell v2 API. Implement basic
structures and List method.
Provide tests and documentation.
For #29
=> Add floatingips package with List method

selvpcclient/resell/v2/floatingips/doc.go, selvpcclient/resell/v2/floatingips/request_opts.go, selvpcclient/resell/v2/floatingips/requests.go, selvpcclient/resell/v2/floatingips/testing/fixtures.go, selvpcclient/resell/v2/floatingips/testing/request_test.go
Add method to create floating ips in the project.
Add doc example and documentation example.
For #29
=> Add Resell V2 API floating ips Create method

selvpcclient/resell/v2/subnets/doc.go, selvpcclient/resell/v2/subnets/requests.go, selvpcclient/resell/v2/subnets/schemas.go, selvpcclient/resell/v2/subnets/testing/fixtures.go, selvpcclient/resell/v2/subnets/testing/request_test.go
Add subnets package with Get method and basic Subnet structure.
For #30
=> Resell V2 - add subnets Get method

selvpcclient/resell/v2/subnets/doc.go, selvpcclient/resell/v2/subnets/requests.go, selvpcclient/resell/v2/subnets/testing/request_test.go
Add method for deleting a single subnet.
Add test and doc example.
For #30
=> Resell V2 API - add subnets Delete method

selvpcclient/resell/v2/licenses/doc.go, selvpcclient/resell/v2/licenses/requests.go, selvpcclient/resell/v2/licenses/schemas.go, selvpcclient/resell/v2/licenses/testing/fixtures.go, selvpcclient/resell/v2/licenses/testing/requests_test.go
Fix License ID field type and add List method.
For #31
=> Add Resell V2 licenses List method and fixes

selvpcclient/resell/v2/licenses/doc.go, selvpcclient/resell/v2/licenses/requests.go, selvpcclient/resell/v2/licenses/testing/requests_test.go
Add delete method for the licenses package with test and doc example.
For #31
=> Resell V2 - add licenses delete method

README.md
Add more info about what objects of API are supported.
For #43
=> Expand readme documentation

selvpcclient/resell/v2/users/testing/fixtures.go, selvpcclient/resell/v2/users/testing/requests_test.go
Add tests with errors.
For #54
=> Resell V2 Users - add more tests

selvpcclient/resell/v2/subnets/testing/fixtures.go, selvpcclient/resell/v2/subnets/testing/request_test.go, selvpcclient/resell/v2/users/testing/requests_test.go
Add tests for error cases.
Also rename some tests in the users package.
For #54
=> Resell V2 subnets - add more tests

selvpcclient/resell/v2/quotas/testing/fixtures.go, selvpcclient/resell/v2/quotas/testing/requests_test.go
Add tests for the error cases.
For #54
=> Resell V2 quotas - add more tests

selvpcclient/resell/v2/licenses/testing/fixtures.go, selvpcclient/resell/v2/licenses/testing/requests_test.go
Add tests for error cases.
For #54
=> Resell V2 licenses - add more tests

selvpcclient/resell/v2/floatingips/testing/fixtures.go, selvpcclient/resell/v2/floatingips/testing/request_test.go
Add tests with error cases.
For #54
=> Resell V2 floatingips - add more tests

selvpcclient/resell/v2/roles/doc.go, selvpcclient/resell/v2/roles/requests.go, selvpcclient/resell/v2/roles/testing/fixtures.go, selvpcclient/resell/v2/roles/testing/requests_test.go
Add roles packages ListUser method, add doc examples, fix some roles
tests and add new.
For #28
=> Resell V2 - add roles list user method

selvpcclient/resell/v2/roles/doc.go, selvpcclient/resell/v2/roles/requests.go, selvpcclient/resell/v2/roles/requests_opts.go, selvpcclient/resell/v2/roles/testing/fixtures.go, selvpcclient/resell/v2/roles/testing/requests_test.go
Add method to create many roles.
Add doc example and tests.
For #28
=> Resell V2 roles - add create bulk method

README.md, selvpcclient/resell/v2/traffic/doc.go, selvpcclient/resell/v2/traffic/requests.go, selvpcclient/resell/v2/traffic/schemas.go, selvpcclient/resell/v2/traffic/testing/fixtures.go, selvpcclient/resell/v2/traffic/testing/requests_test.go, selvpcclient/selvpc.go
Add package to retrieve domain traffic from the Resell V2 API.
For #44
=> Resell V2 - add traffic package

selvpcclient/resell/v2/capabilities/doc.go, selvpcclient/resell/v2/capabilities/requests.go, selvpcclient/resell/v2/capabilities/schemas.go, selvpcclient/resell/v2/capabilities/testing/fixtures.go, selvpcclient/resell/v2/capabilities/testing/request_test.go
Add cababilites package with a single Get method.
For #42
=> Resell V2 - add cababilites package

selvpcclient/resell/v2/tokens/doc.go, selvpcclient/resell/v2/tokens/requests.go, selvpcclient/resell/v2/tokens/requests_opts.go, selvpcclient/resell/v2/tokens/schemas.go, selvpcclient/resell/v2/tokens/testing/fixtures.go, selvpcclient/resell/v2/tokens/testing/requests_test.go
Add tokens package with Create method.
Add tests and doc examples.
For #41
=> Resell V2 - add tokens package

selvpcclient/selvpc.go
Some of the packages should be able to add query parameters to API
requests.
This commit adds common methods to the selvpcclient/selvpc.go that will
allow them to do so.
For #73
=> Add common way to append query params

selvpcclient/resell/v2/capabilities/schemas.go
Add IsPrivate field into capabilities's zone structure.
For #79
=> Resell V2 capabilities: add private zones support

README.md, selvpcclient/resell/v2/vrrpsubnets/doc.go, selvpcclient/resell/v2/vrrpsubnets/requests.go, selvpcclient/resell/v2/vrrpsubnets/schemas.go, selvpcclient/resell/v2/vrrpsubnets/testing/fixtures.go, selvpcclient/resell/v2/vrrpsubnets/testing/requests_test.go
Add vvrpsubnets package with Get method and basic VRRPSubnet structure.
For #78
=> Resell V2 - add VRRP subnets Get method

selvpcclient/resell/v2/vrrpsubnets/doc.go, selvpcclient/resell/v2/vrrpsubnets/requests.go, selvpcclient/resell/v2/vrrpsubnets/requests_opts.go, selvpcclient/resell/v2/vrrpsubnets/testing/fixtures.go, selvpcclient/resell/v2/vrrpsubnets/testing/requests_test.go
Add vvrpsubnets List method and ListOpts structure.
For #78
=> Resell V2 - add VRRP subnets List method

selvpcclient/resell/v2/floatingips/testing/requests_test.go, selvpcclient/resell/v2/licenses/testing/requests_test.go, selvpcclient/resell/v2/projects/testing/requests_test.go, selvpcclient/resell/v2/subnets/testing/requests_test.go
Use correct method names in some Tests error messages.
=> Tests: fix error messages

selvpcclient/resell/v2/vrrpsubnets/doc.go, selvpcclient/resell/v2/vrrpsubnets/requests.go, selvpcclient/resell/v2/vrrpsubnets/requests_opts.go, selvpcclient/resell/v2/vrrpsubnets/testing/fixtures.go, selvpcclient/resell/v2/vrrpsubnets/testing/requests_test.go
Add vrrpsubnets Create method and needed structures.
For #78
=> Resell V2 - add VRRP subnets Create method

selvpcclient/resell/v2/vrrpsubnets/doc.go, selvpcclient/resell/v2/vrrpsubnets/requests.go, selvpcclient/resell/v2/vrrpsubnets/testing/requests_test.go
Add vrrpsubnets Delete method and.
For #78
=> Resell V2 - add VRRP subnets Delete method

selvpcclient/resell/v2/projects/requests_opts.go, selvpcclient/resell/v2/projects/testing/fixtures.go, selvpcclient/resell/v2/projects/testing/requests_test.go
Add AutoQuotas parameter to the projects.CreateOpts structure with unit test.
For #87
=> Resell V2: add auto_quotas parameter for projects

selvpcclient/resell/v2/projects/testing/fixtures.go
Fix testing fixtures for Create method in the projects package.
=> Resell V2: fix test fixtures in projects package

.travis.yml
Use Go 1.11 release and add Gocritic linter.
=> CI: update Go and add Gocritic

selvpcclient/resell/v2/projects/schemas.go, selvpcclient/resell/v2/quotas/schemas.go
Fix formatting issues in Resell V2 projects and quotas.
=> GoFmt: fix projects and quotas schemas.

selvpcclient/selvpc.go
Use "go-selvpcclient" for the application name.
=> SelVPC: update AppName

selvpcclient/resell/v2/keypairs/doc.go, selvpcclient/resell/v2/keypairs/requests.go, selvpcclient/resell/v2/keypairs/requests_opts.go, selvpcclient/resell/v2/keypairs/testing/fixtures.go, selvpcclient/resell/v2/keypairs/testing/requests_test.go
Add Create method for the "keypairs" package with tests and doc example.
For #110
=> Resell V2 - add Keypairs Create method

selvpcclient/resell/v2/crossregionsubnets/doc.go, selvpcclient/resell/v2/crossregionsubnets/requests.go, selvpcclient/resell/v2/crossregionsubnets/requests_opts.go, selvpcclient/resell/v2/crossregionsubnets/testing/fixtures.go, selvpcclient/resell/v2/crossregionsubnets/testing/requests_test.go
Add crossregionsubnets List method and ListOpts structure.
Also this commit fixes fields order for Get method fixtures.
For #106
=> Resell V2 - add cross-region subnets List method

selvpcclient/resell/v2/crossregionsubnets/doc.go, selvpcclient/resell/v2/crossregionsubnets/requests.go, selvpcclient/resell/v2/crossregionsubnets/requests_opts.go, selvpcclient/resell/v2/crossregionsubnets/testing/fixtures.go, selvpcclient/resell/v2/crossregionsubnets/testing/requests_test.go
Add crossregionsubnets Create method and needed structures.
For #106
=> Resell V2 - add cross-region subnets Create method

go.mod
Initialize go.mod in repository.
For #122
=> Go modules: add go.mod

.travis.yml, go.mod
=> CI: use v1.15.0 release of GolangCI

selvpcclient/resell/v2/users/doc.go, selvpcclient/resell/v2/users/requests.go, selvpcclient/resell/v2/users/testing/fixtures.go, selvpcclient/resell/v2/users/testing/requests_test.go
Add support for new enpoint `users/USER_ID`.
=> Add support method Get for single user

selvpcclient/selvpc.go
=> Version: bump to 1.9.0

.gitignore, .golangci.yml, .travis.yml
Update GolangCI version in .travis.yml.
Update .golangci.yml config.
Add .gitignore.
=> CI: use v1.19.1 release of GolangCI

selvpcclient/resell/v2/licenses/schemas.go, selvpcclient/resell/v2/licenses/testing/fixtures.go
Add NetworkID and SubnetID fields into License struct.
Update tests for licenses package.
For #139
=> Resell V2 Licenses: add network and subnet data

.golangci.yml, .travis.yml
Use newer GolangCI-Lint in .travis.yml.
=> Update GolangCI-Lint to v1.23.8

.travis.yml
Add new Go versions into .travis.yml.
=> Add 1.13, 1.14 Go versions into .travis.yml

selvpcclient/selvpc.go
Update version for the default user-agent header.
=> Set 1.10.0 version in selvpc.go

selvpcclient/selvpc.go
Update version for the default user-agent header.
=> Set 1.11.0 version in selvpc.go

selvpcclient/selvpc.go
Update version for the default user-agent header.
=> Set 1.12.0 version in selvpc.go

selvpcclient/selvpc.go
Fix version for the default user-agent header.
=> Set 1.11.1 version in selvpc.go

.golangci.yml, .travis.yml, go.mod, selvpcclient/resell/v2/quotas/requests_opts.go, selvpcclient/selvpc.go
=> Fix linters and change golang versions

selvpcclient/resell/v2/tokens/doc.go, selvpcclient/resell/v2/tokens/requests_opts.go
=> Rename field domain to account

go.mod
=> Use Go 1.14 in go.mod

selvpcclient/selvpc.go
Prepare library for the new release.
=> Set AppVersion to 1.12.0

selvpcclient/resell/v2/capabilities/schemas.go, selvpcclient/resell/v2/capabilities/testing/requests_test.go
=> Remove redundant fields from capabilities
